name: Push SQL to AEP

on:
  push:
    branches:
      - main
    paths:
      - queries/*.sql

jobs:
  push-to-aep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for accurate git diff

      - name: Detect Updated SQL Files
        id: file_finder
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep "^queries/.*\.sql" || true)
          echo "Detected SQL files:"
          echo "$FILES"
          FILES_SINGLE_LINE=$(echo "$FILES" | paste -sd " " -)
          echo "sql_files=$FILES_SINGLE_LINE" >> $GITHUB_OUTPUT

      - name: Stop if no SQL file changed
        if: ${{ steps.file_finder.outputs.sql_files == '' }}
        run: |
          echo "No SQL files updated. Skipping AEP push."
          exit 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script to Push SQL to AEP
        env:
          SQL_FILE_PATH: ${{ steps.file_finder.outputs.sql_files }}
          AEP_AUTH_TOKEN: ${{ secrets.AEP_AUTH_TOKEN }}
          AEP_API_KEY: ${{ secrets.AEP_API_KEY }}
          AEP_ORG_ID: ${{ secrets.AEP_ORG_ID }}
          AEP_SANDBOX: ${{ secrets.AEP_SANDBOX }}
        run: python scripts/push_to_aep.py
